# Generated by Django 4.1.7 on 2025-09-15 10:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True)),
                ('criteria', djongo.models.fields.JSONField(default=dict)),
                ('points_reward', models.IntegerField(default=0)),
                ('achievement_type', models.CharField(choices=[('milestone', 'Milestone'), ('consistency', 'Consistency'), ('challenge', 'Challenge'), ('social', 'Social')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('leaderboard_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time'), ('challenge', 'Challenge Specific')], max_length=50)),
                ('category', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('leaderboard_id', models.CharField(max_length=24)),
                ('participant_id', models.IntegerField()),
                ('participant_type', models.CharField(choices=[('user', 'User'), ('team', 'Team')], max_length=20)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('achievement_id', models.CharField(max_length=24)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress_data', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
