# Generated by Django 4.1.7 on 2025-09-15 10:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('steps', 'Step Challenge'), ('duration', 'Duration Challenge'), ('points', 'Points Challenge'), ('custom', 'Custom Challenge')], max_length=50)),
                ('target_value', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participating_teams', djongo.models.fields.JSONField(default=list)),
                ('rewards', djongo.models.fields.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('captain_id', models.IntegerField()),
                ('max_members', models.IntegerField(default=10)),
                ('is_public', models.BooleanField(default=True)),
                ('team_code', models.CharField(max_length=8, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=24)),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('points_contributed', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
